# Final Project: Sentiment Analysis on COVID-19 Vaccine with Tweets

- Number of records
- Number of columns
- Statistical summary of response variable
- Statistical summary of potential predictor variables (if there are a large number of predictors, select the top 10)
- Note: Summarize categorical variables with counts and percentages for each level and summarize numerical variables with mean/quantiles/standard deviation. Include up to five helpful graphs

In [31]:
import pandas
import os
import pandas as pd

# Getting the current directory of interest
thisdir = '/project/ds5559/twitter_sentiment_analysis_group/'

dfALL = pd.DataFrame()

# r=root, d=directories, f = files
for r, d, f in os.walk(thisdir):
    for file in f:
        if file.endswith(".csv"):
            filedir = os.path.join(r, file)
            print(filedir)
            tmpdf = pd.read_csv(filedir, index_col = 0)
            dfALL = pd.concat([dfALL, tmpdf])

print(len(dfALL.index))

/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210318_0309.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210320_1148.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210318_1359.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_early_attempt.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210319_1252.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210319_2253.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210320_0902.csv

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (0,4,6,14) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210317_1203.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210321_0531.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210321_0055.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210321_1044.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210318_1401.csv
/project/ds5559/twitter_sentiment_analysis_group/hashtag_output_210320_4511.csv
1021687

## Data Frame Dimension

In [32]:
# data_cx.shape
print(f'Our data frame contains {dfALL.shape[0]} rows and {dfALL.shape[1]} columns')

Our data frame contains 1021687 rows and 19 columns

In [34]:
data = dfALL.copy()
data.head(2)

,scraped_hashtag,scraped_order,created_at,id_str,text,truncated,in_reply_to_screen_name,retweet_count,favorite_count,lang,screen_name,user_name,user_description,user_verified,user_followers_count,hashtags,symbols,og_tweet_by,og_tweet_truncated
0,#vaccine,0.0,Thu Mar 18 01:05:26 +0000 2021,1372353417507565569,BIG NEWS from @GovSisolak: #COVID19Vaccine eli...,True,NaN,0.0,0.0,en,atdleft,Andrew Davey,"Muckraker, troublemaker, & no-BS-taker. I'm a ...",False,2034.0,['COVID19Vaccine'],[],NaN,NaN
1,#vaccine,0.0,Thu Mar 18 01:05:15 +0000 2021,1372353373123407879,@TerryBrady2097 This #Health #COVID19 #Vaccine...,True,TerryBrady2097,0.0,0.0,en,pully8,rose lane,NaN,False,513.0,"['Health', 'COVID19', 'Vaccine', 'agedcare']",[],NaN,NaN

In [30]:
data.columns

Index(['scraped_hashtag', 'scraped_order', 'created_at', 'id_str', 'text',
       'truncated', 'in_reply_to_screen_name', 'retweet_count',
       'favorite_count', 'lang', 'screen_name', 'user_name',
       'user_description', 'user_verified', 'user_followers_count', 'hashtags',
       'symbols', 'og_tweet_by', 'og_tweet_truncated'],
      dtype='object')

Goals:
- Statistical summary of potential predictor variables (if there are a large number of predictors, select the top 10)
  - Summarize categorical variables with counts and percentages for each level and summarize numerical variables with mean/quantiles/standard deviation. Include up to five helpful graphs


- Arshiya: reweet_count, favorite_count
- David: created_at, scraped_hashtag
- Kip: text, user_follower_count, user_description
- Tiger: hashtags, lang

## Response Variable

What we are planning to do is an unsupervised learning process, which aims to extract the sentiments of the general public towards the COVID-19 vaccine.

## Predictor Variable
Our main predictor variable will be the `text` column

In [15]:
data.text.describe()

count                                                241934
unique                                                55401
top       RT @DrEricDing: VACCINE ESCAPE OF VARIANTS vs ...
freq                                                   2975
Name: text, dtype: object

In [29]:
data.sort_values('text')

,scraped_hashtag,scraped_order,created_at,id_str,text,truncated,in_reply_to_screen_name,retweet_count,favorite_count,lang,screen_name,user_name,user_description,user_verified,user_followers_count,hashtags,symbols,og_tweet_by,og_tweet_truncated
70037,mrna,49,Sun Mar 21 06:52:30 +0000 2021,1373527921843789825,!! BOMBSHEL !! MAJOR ALERT !!\n\n#Moderna Chie...,True,NaN,3,1,en,sheasie,Xolotl Tlaloc (XTC) Ⓥ,knowledge is power\n\nxolotltlaloc @ https://t...,False,387,['Moderna'],[],NaN,NaN
41392,sputnikv,55,Sat Mar 20 08:21:51 +0000 2021,1373188022993305600,""" The EU has managed to vaccinate only around ...",True,NaN,0,0,en,laparla,Karla,#Politics #ClimateChange #AMLOVER #FreePalest...,False,2276,[],[],NaN,NaN
74935,sputnikv,54,Sat Mar 20 08:21:51 +0000 2021,1373188022993305600,""" The EU has managed to vaccinate only around ...",True,NaN,0,0,en,laparla,Karla,#Politics #ClimateChange #AMLOVER #FreePalest...,False,2276,[],[],NaN,NaN
608,vaccine,0,Sat Mar 20 14:33:07 +0000 2021,1373281452410896385,"""""When I Virus Vaccine Doctor Disease Patient""...",False,NaN,0,0,en,SUSHANT32310609,LDGSD SUSHANTA MANDAL LDGSD,Self Help is the best help,False,0,[],[],NaN,NaN
34139,covid19vaccine,46,Sat Mar 20 22:36:17 +0000 2021,1373403047028793348,"""#France policy on #AstraZeneca #vaccine ‘comp...",True,NaN,0,0,en,tomyoritaka,Thomas (Tom) Yoritaka,Founding Partner @UCLDiscentiaCap | Governor o...,False,644,"['France', 'AstraZeneca', 'vaccine', 'UK']",[],NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11451,covid19 pfizer,7,Sat Mar 20 19:27:05 +0000 2021,1373355430764802052,🧿🧿 The real award 🥇🥇 We are so grateful to the...,True,NaN,0,3,en,KalkanliCandan,Candan Kalkanli,"@JohnKalkanli’s mother, nature & animal & trav...",False,54,"['ÖzlemTüreci', 'UğurŞahin', 'Turkey', 'Türkiy...",[],NaN,NaN
33093,covid19 biontech,25,Sat Mar 20 19:27:05 +0000 2021,1373355430764802052,🧿🧿 The real award 🥇🥇 We are so grateful to the...,True,NaN,0,3,en,KalkanliCandan,Candan Kalkanli,"@JohnKalkanli’s mother, nature & animal & trav...",False,54,"['ÖzlemTüreci', 'UğurŞahin', 'Turkey', 'Türkiy...",[],NaN,NaN
33985,covid19 biontech,25,Fri Mar 19 06:45:54 +0000 2021,1372801487638724612,🩺 Thank you #HongKong Government for facilitat...,True,NaN,9,32,en,EUinHKandMO,European Union Office to Hong Kong and Macao,🇪🇺🇭🇰🇲🇴 Official Twitter of the EU Office to Ho...,False,2178,"['HongKong', 'BioNTech', 'Vaccines']",[],NaN,NaN
19561,covid19 biontech,26,Fri Mar 19 06:45:54 +0000 2021,1372801487638724612,🩺 Thank you #HongKong Government for facilitat...,True,NaN,9,29,en,EUinHKandMO,European Union Office to Hong Kong and Macao,🇪🇺🇭🇰🇲🇴 Official Twitter of the EU Office to Ho...,False,2177,"['HongKong', 'BioNTech', 'Vaccines']",[],NaN,NaN
19274,covid19 biontech,26,Fri Mar 19 06:45:54 +0000 2021,1372801487638724612,🩺 Thank you #HongKong Government for facilitat...,True,NaN,9,31,en,EUinHKandMO,European Union Office to Hong Kong and Macao,🇪🇺🇭🇰🇲🇴 Official Twitter of the EU Office to Ho...,False,2179,"['HongKong', 'BioNTech', 'Vaccines']",[],NaN,NaN

In [25]:
data[['scraped_hashtag','text']].groupby('scraped_hashtag').count().sort_values('text', ascending = False)

                         text
scraped_hashtag
vaccinessavelives        8000
covid19 biontech         6000
covid19 astrazeneca      6000
covid-19 biontech        6000
covid-19 astrazeneca     6000
...                       ...
pharmagreed                43
biontechvaccine            12
iwillgetvaccinated         11
astrazenecacovidvaccine    11
modernacovidvaccine         8

[72 rows x 1 columns]

In [27]:
data[['scraped_hashtag','retweet_count']].groupby('scraped_hashtag').mean().sort_values('retweet_count', ascending = False)

                         retweet_count
scraped_hashtag
endthelockdown             1521.651000
vaccine                     887.386250
covid19 biontech            716.755667
covidiots                   686.889750
vaccination                 630.366000
...                                ...
notocoronavirusvaccines       0.061674
biontechvaccine               0.000000
modernacovidvaccine           0.000000
iwillgetvaccinated            0.000000
astrazenecacovidvaccine       0.000000

[72 rows x 1 columns]